# Generated by Django 5.2.5 on 2025-08-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('job_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('company_id', models.CharField(db_index=True, max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('articles_found', models.PositiveIntegerField(default=0)),
                ('articles_saved', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000)),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('company_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], db_index=True, default='neutral', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.FloatField(db_index=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('search_vector', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_api.newscategory')),
                ('tags', models.ManyToManyField(blank=True, to='news_api.newstag')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['published_at'], name='news_api_ne_publish_c7793f_idx'), models.Index(fields=['company_id', 'published_at'], name='news_api_ne_company_e7d145_idx'), models.Index(fields=['sentiment', 'published_at'], name='news_api_ne_sentime_0e6a6f_idx'), models.Index(fields=['popularity_score'], name='news_api_ne_popular_2ba226_idx'), models.Index(fields=['created_at'], name='news_api_ne_created_1a7923_idx'), models.Index(fields=['is_active', 'published_at'], name='news_api_ne_is_acti_cb2cd0_idx')],
            },
        ),
    ]
